# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  # - name: "SpacyNLP"
  #   model: "vi_core_news_md"
  #   case_sensitive: false
  # - name: SpacyTokenizer
  # - name: "vi_tokenizer.VietnameseTokenizer"
    # config with HFTmodel
  - name: "HFTransformersNLP"
    model_name: "bert"
    model_weights: "E:/web/rasa_2_module/bert-base-vietnamese-uncased"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    ranking_length: 3
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.5
    ambiguity_threshold: 0.1


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy






  # - name: WhitespaceTokenizer
  # - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: word
  #   min_ngram: 1  
  #   max_ngram: 4
  # - name: DIETClassifier
  #   epochs: 100
  #   ranking_length: 3
  # - name: FallbackClassifier
  #   threshold: 0.5
  #   ambiguity_threshold: 0.1